Resolve "Pipeline fails on new chart"

diff --git a/templates/package-tests.yml b/templates/package-tests.yml
--- a/templates/package-tests.yml
+++ b/templates/package-tests.yml
@@ -123,10 +123,28 @@ chart update check:
     # run pipeline on merge request events
     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
   script:
-    - echo -e "\e[0Ksection_start:`date +%s`:package_checkout1[collapsed=true]\r\e[0KPackage $CI_MERGE_REQUEST_TARGET_BRANCH_NAME Checkout"
+    # change to target branch and check if Chart.yaml or Changelog missing. If so, check source.
+    - echo -e "\e[0Ksection_start:`date +%s`:chart_changelog_checks[collapsed=true]\r\e[0KHeader Searching for Chart.yaml/CHANGELOG mismatches"
     - git fetch && git checkout ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
+    - |
+      if [ ! -f "chart/Chart.yaml" ] || [ ! -f "CHANGELOG.md" ]; then
+        # change to source branch and check if Chart.yaml or Changelog missing. If one or both are missing, fail.
+        git fetch && git checkout ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}
+        if [ ! -f "chart/Chart.yaml" ] || [ ! -f "CHANGELOG.md" ]; then
+          echo -e "\e[0Ksection_end:`date +%s`:chart_changelog_checks\r\e[0K"
+          echo -e "\e[31mFAIL: Package must have chart/Chart.yaml and CHANGELOG.md\e[0m"
+          exit 1
+        else
+          # target branch is missing Chart.yaml or Changelog. Exit with notice.
+          echo -e "\e[0Ksection_end:`date +%s`:chart_changelog_checks\r\e[0K"
+          echo -e "\e[31mNOTICE: Chart.yaml or Changelog not found in ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}, skipping update check\e[0m"
+          exit 0
+        fi
+        # return to target branch
+        git fetch && git checkout ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
+      fi
     - cp CHANGELOG.md /tmp/CHANGELOG.md
-    - echo -e "\e[0Ksection_end:`date +%s`:package_checkout1\r\e[0K"
+    - echo -e "\e[0Ksection_end:`date +%s`:chart_changelog_checks\r\e[0K"
     - DEFAULT_BRANCH_VERSION=$(yq e '.version' chart/Chart.yaml)
     - 'echo "Chart Version: $DEFAULT_BRANCH_VERSION"'
     - echo -e "\e[0Ksection_start:`date +%s`:package_checkout2[collapsed=true]\r\e[0KPackage MR Checkout"
