Resolve "Create IaC and Pipeline for Air Gap Infrastructure"

diff --git a/infrastructure/templates.yaml b/infrastructure/templates.yaml
--- a/infrastructure/templates.yaml
+++ b/infrastructure/templates.yaml
@@ -81,18 +81,20 @@ include:
   after_script:
     - echo -e "\e[0Ksection_start:`date +%s`:terraform_destroy_workspace[collapsed=true]\r\e[0K\e[33;1mTerraform Destroy Workspace\e[37m"
     - cd ${TF_ROOT}
-    # Loop to retry terraform workspace destory
+    # Loop to retry terraform workspace destroy
     - |
       set -e
       attempt_counter=0
       max_attempts=2
-      until [ $(terraform workspace select default >/dev/null && terraform workspace delete "${TF_VAR_env}" >/dev/null; echo $?) -eq 0 ]; do
-        if [ ${attempt_counter} == ${max_attempts} ];then
-          echo "Error destroying terraform workspace"
-          exit 1
-        fi
-        attempt_counter=$(($attempt_counter+1))
-        echo "❌ Attempt FAILED to destroy workspace will retry in 30 seconds"
-        sleep 30
-      done
+      terraform workspace select default
+      terraform workspace delete "${TF_VAR_env}"
+     #until [ $(terraform workspace select default >/dev/null && terraform workspace delete "${TF_VAR_env}" >/dev/null; echo $?) -eq 0 ]; do
+     #  if [ ${attempt_counter} == ${max_attempts} ];then
+     #    echo "Error destroying terraform workspace"
+     #    exit 1
+     #  fi
+     #  attempt_counter=$(($attempt_counter+1))
+     #  echo "❌ Attempt FAILED to destroy workspace will retry in 30 seconds"
+     #  sleep 30
+     #done
     - echo -e "\e[0Ksection_end:`date +%s`:terraform_destroy_workspace\r\e[0K"
